# Generated by Django 5.0.1 on 2024-02-01 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=25, unique=True)),
                ('PublishedDate', models.DateField()),
                ('Genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('MembershipDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('DetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('NumberOfPages', models.IntegerField()),
                ('Publisher', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=25)),
                ('BookID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorrowDate', models.DateField()),
                ('ReturnDate', models.DateField(blank=True, null=True)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.user')),
            ],
        ),
    ]
